#@ 35 local pipeline runs
# --- run pipelines locally --------------------------------------------------

#: cil [scope]           run .gitlab-ci.yml locally in docker, before pushing
#>   cil                   the whole pipeline
#>   cil -l                list jobs without running anything
#>   cil -j                pick one job with fzf and run it
#>   cil build             run the job named build
#>   cil -n build          run build plus the jobs it needs
#>   cil -s build          same, with your ssh agent forwarded
#>   cil -v                write a variables template from the pipeline itself
#>
#>   -s is per run, never default. it mounts $SSH_AUTH_SOCK into the job so
#>   a script can git clone or ssh as you. the container gets the socket,
#>   not the key - but the agent still signs whatever it is asked to, and
#>   the scripts include templates you did not write. use it for the one
#>   job that needs it, not for the whole pipeline.
#>
#>   with -s, also set in ~/.gitlab-ci-local/variables.yml:
#>     SSH_AUTH_SOCK: /ssh-agent
#>
#>   variables the real pipeline gets from GitLab must be supplied locally:
#>     ./.gitlab-ci-local-variables.yml   per repo   (never commit this)
#>     ~/.gitlab-ci-local/variables.yml   shared across repos
#>
#>   keep both out of git for good:
#>     git config --global core.excludesFile ~/.config/git/ignore
#>     printf '%s\n' .gitlab-ci-local/ .gitlab-ci-local-variables.yml \
#>       >> ~/.config/git/ignore
cil() {
    command -v gitlab-ci-local >/dev/null || {
        echo "cil: gitlab-ci-local not installed (add pkgs.gitlab-ci-local)" >&2; return 1; }
    [ -f .gitlab-ci.yml ] || { echo "cil: no .gitlab-ci.yml here" >&2; return 1; }
    docker info >/dev/null 2>&1 || { echo "cil: docker daemon not reachable" >&2; return 1; }

    # SSH is opt-in per run, never default: mounting the agent socket lets
    # every script in the pipeline - including included templates you did not
    # write - sign with your key. The container gets the socket, not the key,
    # but the agent will still sign whatever it is asked to.
    local ssh_opt=()
    if [ "${1:-}" = "-s" ] || [ "${1:-}" = "--ssh" ]; then
        shift
        if [ -z "${SSH_AUTH_SOCK:-}" ]; then
            echo "cil: no ssh-agent running (SSH_AUTH_SOCK unset)" >&2
            return 1
        fi
        ssh_opt=(--volume "$SSH_AUTH_SOCK:/ssh-agent")
        echo "cil: forwarding the ssh agent - jobs can sign as you"
    fi

    local job
    case "${1:-}" in
        -v|--vars)
            _cil_vars_template ;;
        -l|--list)
            gitlab-ci-local "${ssh_opt[@]}" --list ;;
        -j|--job)
            # column 1 of --list is the job name; drop the header row
            job=$(gitlab-ci-local --list 2>/dev/null \
                  | awk 'NR > 1 && NF { print $1 }' \
                  | fzf --prompt='job> ' --height=40%) || return 1
            [ -n "$job" ] || return 1
            gitlab-ci-local "${ssh_opt[@]}" "$job" ;;
        -n|--needs)
            shift
            [ $# -gt 0 ] || { echo "cil -n needs a job name" >&2; return 1; }
            gitlab-ci-local "${ssh_opt[@]}" --needs "$@" ;;
        *)
            gitlab-ci-local "${ssh_opt[@]}" "$@" ;;
    esac
}

# Every variable the merged pipeline references, minus the ones GitLab-CI-local
# already provides. Written as a template you fill in - the tool cannot know
# your credentials, but it can tell you exactly which ones it will look for.
_cil_vars_template() {
    command -v gitlab-ci-local >/dev/null || {
        echo "cil: gitlab-ci-local not installed" >&2; return 1; }
    [ -f .gitlab-ci.yml ] || { echo "cil: no .gitlab-ci.yml here" >&2; return 1; }

    local out=.gitlab-ci-local-variables.yml merged names

    merged=$(gitlab-ci-local --preview 2>/dev/null)
    [ -n "$merged" ] || { echo "cil: --preview produced nothing" >&2; return 1; }

    # $VAR and ${VAR}, then drop the ones the tool sets for you.
    # shellcheck disable=SC2016   # the literal $ and backticks are intended
    names=$(printf '%s\n' "$merged" \
        | grep -oE '\$\{?[A-Z][A-Z0-9_]{2,}\}?' \
        | tr -d '${}' \
        | sort -u \
        | grep -vxE 'CI_PROJECT_(DIR|NAME|PATH|PATH_SLUG|ID|NAMESPACE|URL)' \
        | grep -vxE 'CI_COMMIT_(SHA|SHORT_SHA|REF_SLUG|TIMESTAMP|MESSAGE|TITLE|AUTHOR)' \
        | grep -vxE 'CI_JOB_(NAME|STAGE|ID|STATUS)|CI_PIPELINE_(ID|IID)' \
        | grep -vxE 'CI_SERVER_(URL|HOST|PORT|PROTOCOL)|CI_API_V4_URL|CI_REGISTRY|GITLAB_CI' \
        | grep -vxE 'CI_PIPELINE_SOURCE|CI_COMMIT_BRANCH|CI_COMMIT_REF_NAME|CI_DEFAULT_BRANCH')

    if [ -e "$out" ]; then
        echo "cil: $out exists - writing $out.new instead" >&2
        out=$out.new
    fi

    # shellcheck disable=SC2016   # markdown backticks in the header
    {
        printf '# Generated by `cil -v` from the merged pipeline.\n'
        printf '# Every variable below is referenced by a job. Fill in what you\n'
        printf '# have; leave the rest and those jobs will behave as if unset -\n'
        printf '# which is often what you want, since rules gate on them.\n'
        printf '#\n'
        printf '# Secrets belong in ~/.gitlab-ci-local/variables.yml instead:\n'
        printf '# that file lives outside every repo and cannot be committed.\n'
        printf '\n'
        printf '# --- the situation you are simulating ---\n'
        printf 'CI_PIPELINE_SOURCE: push          # or merge_request_event, schedule\n'
        printf 'CI_COMMIT_BRANCH: %s\n' "$(git branch --show-current 2>/dev/null)"
        printf 'CI_COMMIT_REF_NAME: %s\n' "$(git branch --show-current 2>/dev/null)"
        printf 'CI_DEFAULT_BRANCH: main\n'
        printf '\n'
        printf '# --- referenced by this pipeline ---\n'
        printf '%s\n' "$names" | while read -r n; do
            [ -n "$n" ] || continue
            printf '%s: ""\n' "$n"
        done
    } > "$out"

    printf 'wrote %s  (%s variables)\n' "$out" "$(grep -c ': ' "$out")"
    printf 'gitignore it: it is per-repo and will hold values you paste in.\n'
}
